# Generated by Django 5.0.4 on 2024-05-08 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPurchase',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('student_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='coupon_code')),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
