# Generated by Django 5.0.4 on 2024-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_couponpurchase_no_of_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
