# Generated by Django 5.0.4 on 2024-05-08 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_couponpurchase_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
