# Generated by Django 5.0.4 on 2024-05-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_couponpurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpurchase',
            name='student_ids',
            field=models.CharField(blank=True, null=True, verbose_name=models.CharField(max_length=255)),
        ),
    ]
