# Generated by Django 5.0.4 on 2024-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_couponpurchase_student_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpurchase',
            name='student_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
