# Generated by Django 5.0.4 on 2024-05-09 09:15

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_couponpurchase_student_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponpurchase',
            name='expired_date',
        ),
        migrations.AlterField(
            model_name='couponpurchase',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=Account.models.coupon_file_path),
        ),
    ]
