# Generated by Django 5.0.4 on 2024-05-09 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_couponpurchase_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='expired_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
