# Generated by Django 5.0.4 on 2024-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_remove_couponpurchase_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
