# Generated by Django 5.0.4 on 2024-05-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_couponpurchase_coupon_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
