# Generated by Django 5.0.4 on 2024-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_post_file_alter_post_image_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
    ]
