# Generated by Django 5.0.4 on 2024-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='video',
        ),
    ]
