# Generated by Django 5.0.4 on 2024-05-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
