# Generated by Django 5.0.4 on 2024-05-13 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_alter_books_book_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cloudinary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_imageUrl',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdf_files/'),
            preserve_default=False,
        ),
    ]
