# Generated by Django 5.0.4 on 2024-05-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_books_cloudinary_url_alter_books_book_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cloudinary_url',
        ),
    ]
