# Generated by Django 5.0.4 on 2024-05-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_remove_books_cloudinary_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponpurchase',
            old_name='coupon_id',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='couponpurchase',
            name='student_ids',
        ),
    ]
