# Generated by Django 5.0.4 on 2024-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0023_coursepurchasecoupon_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='no_of_notifications',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
